name: CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  CI:

    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64

    - name: Check build env
      run: |
        echo "pwd: $(pwd)"
        echo "USER: $USER"
        echo "HOME: $HOME"
        echo "SHELL: $SHELL"
        echo "PATH: $PATH"
        python3 --version
        pip3 --version

    - name: Get pip cache directory
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"

    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-python-3.8-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-3.8-${{ hashFiles('**/requirements.txt') }}
          ${{ runner.os }}-python-3.8-

    - name: Setup
      run: |
        # pip install binary to $HOME/.local/bin
        # export PATH="$PATH:$HOME/.local/bin"
        #
        # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
        echo "/home/runner/.local/bin" >> $GITHUB_PATH

